server:
  port: 80
spring:
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/tripdb?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
    - classpath:classpath:/mapper/*.xml
  type-aliases-package:
    - com.ssafy.enjoytrip.*.model