spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tripdb_test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: sql/tripdb_test.sql
