server:
  port: 80
spring:
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/tripdb?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true