server:
  port: 80
spring:
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/tripdb?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ssafy.enjoytrip.*.model.dto, com.ssafy.enjoytrip.*.model.entity
#  com.ssafy.enjoytrip.room.model.entity, com.ssafy.enjoytrip.roompicture.model.entity, com.ssafy.enjoytrip.reservation.model.entity
jwt:
  token:
    secret: "secretKeysadfasfasrv3as2lirjmesrlvasletijmaslvitastmvastushvtststvastvaytdya"
cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_PRIVATE_KEY}
    region:
      static: ${AWS_S3_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    stack:
      auto: false

toss:
  test:
    client-key: test_ck_aBX7zk2yd8yWXEvbYGqVx9POLqKQ
    secret-key: test_sk_7XZYkKL4MrjE2XEXvEWV0zJwlEWR

