spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tripdb_test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver: com.mysql.cj.jdbc.Driver
cloud:
  aws:
    credentials:
      access-key: testAccessKey
      secret-key: testSecretKey
    region:
      static: ap-northeast-2
    s3:
      bucket: testBucket
    stack:
      auto: false
